blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/MrGreensWorkshop/arduinoPico_RasPiPicoW_AlexaEnabledSmartDevices/discussions/new?category=feature-requests
    about: Please submit your Feature request here.
